### ISSUE TITLE
Great job !

### ISSUE THREAD

**Issue by MathieuLeocmach** [yangyushi/read_lif#1]
Hi @yangyushi !
That's a great job you did here. I wanted to isolate this bit of my code for a while and package it independently of "colloids", which is a mess to maintain.
Can you put me as contributor on this project, in case I have new code to contribute?

**Comment by yangyushi** [comment]
Hi @MathieuLeocmach. Thanks for the message and your really nice code! I already added you as a collaborator.

**Comment by Npikielny** [comment]
How could one use colloid/reaf_lif to isolate a specific channel from an image at a specific z value in a z-stack?

**Comment by yangyushi** [comment]
Hi Npikielny,

I am not sure about how to use the lif reader module in [colloids](https://github.com/MathieuLeocmach/colloids). I modified the channel-choosing part of the code.

If I want to use the code from *this repository*, I would probably do something like

```py
import read_lif

reader = read_lif.Reader('lif_file.lif')
series = reader.getSeries()
chosen = series[0]  # choose first image in the lif file
image_3d = chosen.getFrame(channel=0)  # choose the first channel
image_2d = image_3d[:, :, 0]  # choose the first z-stack
```

I hope this helps.

**Comment by Npikielny** [comment]
> Hi Npikielny,
> 
> I am not sure about how to use the lif reader module in [colloids](https://github.com/MathieuLeocmach/colloids). I modified the channel-choosing part of the code.
> 
> If I want to use the code from _this repository_, I would probably do something like
> 
> ```python
> import read_lif
> 
> reader = read_lif.Reader('lif_file.lif')
> series = reader.getSeries()
> chosen = series[0]  # choose first image in the lif file
> image_3d = chosen.getFrame(channel=0)  # choose the first channel
> image_2d = image_3d[:, :, 0]  # choose the first z-stack
> ```
> 
> I hope this helps.

Thank you! Worked like a charm!
