### ISSUE TITLE
Strange behavior on images with >3 channels

### ISSUE THREAD

**Issue by RoganGrant** [yangyushi/read_lif#3]
First of all, thanks for a great utility. It's exceptionally easy to use.

The issue is arguably more of a feature request:
When plotting images with 4 channels, matplotlib renders the images in black and white with strange overlays (see attached). Using 5 or more channels raises the error: `TypeError: Invalid shape (512, 512, 5) for image data`. Is there any easy workaround to this? If not, it would be great to be able to assign LUTs to each channel for highly multiplexed images.

Update: it appears that this is specific to matplotlib, as the channels get mapped to RGBa (this explains the transparency). Being able to assign color scales to each channel would still be very helpful.

<img width="913" alt="Screen Shot 2019-11-04 at 10 40 44 AM" src="https://user-images.githubusercontent.com/16767040/68139385-a75c6580-feef-11e9-84b8-5866cb53d4fe.png">

**Comment by MathieuLeocmach** [comment]
Hi,
Thank you for your encouraging comments.
This a display problem, whereas the job of read_lif is only to extract data and metadata from the LIF file. You should be asking your question to matplotlib instead (https://discourse.matplotlib.org/)
